### ISSUE TITLE
Crash Game after execute extern lua

### ISSUE THREAD

**Issue by kevink98** [CoderDE/FicsIt-Networks#37] opened 2020-08-03 19:57 UTC
Hi,

I load an extern lua file with the filesystem. After run the code in-game the game freeze and crash. 

When I now try load the savegame, the game crash again after ~30 seconds. In this time I do nothing in the game. 

Here the gamelog: 

[FactoryGame.log](https://github.com/CoderDE/FicsIt-Networks/files/5018165/FactoryGame.log)

**Comment by Panakotta00** [comment] 2020-08-04 11:55
The issue is caused by the same error as the following issue ^^
Duplicate of #33

**Closed** 2020-08-04 11:55 UTC
