### ISSUE TITLE
Issue on FicsIt 0.0.11, using experimental, on client joining

### ISSUE THREAD

**Issue by ebarboni** [CoderDE/FicsIt-Networks#102] opened 2020-11-03 17:51 UTC
Hi,
The following error occurs on host after a client join on 0.0.11 / experimental.
We boths remove all the mods and test for each mod and only FicsIt-Networks is throwing the execption
I'm not sure how to make better report, here the log
```
Version: 135035, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes

Assertion failed: CmdIndexIterator->ChangelistIterator.ChangedIndex - OldChangedIndex <= ArrayChangedCount [File:D:\ws\SB-160502110050-fad\UE4\Engine\Source\Runtime\Engine\Private\RepLayout.cpp] [Line: 1275]

FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
FactoryGame_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:439]
FactoryGame_Win64_Shipping!FRepLayout::PruneChangeList_r() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\replayout.cpp:1458]
FactoryGame_Win64_Shipping!FRepLayout::MergeChangeList() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\replayout.cpp:3250]
FactoryGame_Win64_Shipping!FRepLayout::ReplicateProperties() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\replayout.cpp:871]
FactoryGame_Win64_Shipping!FObjectReplicator::ReplicateProperties() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\datareplication.cpp:1354]
FactoryGame_Win64_Shipping!UActorChannel::ReplicateActor() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\datachannel.cpp:2840]
FactoryGame_Win64_Shipping!UReplicationGraph::ReplicateSingleActor() [d:\ws\sb-160502110050-fad\ue4\engine\plugins\runtime\replicationgraph\source\private\replicationgraph.cpp:1505]
FactoryGame_Win64_Shipping!UReplicationGraph::ReplicateActorListsForConnection_Default() [d:\ws\sb-160502110050-fad\ue4\engine\plugins\runtime\replicationgraph\source\private\replicationgraph.cpp:1153]
FactoryGame_Win64_Shipping!UReplicationGraph::ServerReplicateActors() [d:\ws\sb-160502110050-fad\ue4\engine\plugins\runtime\replicationgraph\source\private\replicationgraph.cpp:830]
FactoryGame_Win64_Shipping!UNetDriver::ServerReplicateActors() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\networkdriver.cpp:4248]
FactoryGame_Win64_Shipping!UNetDriver::TickFlush() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\networkdriver.cpp:510]
FactoryGame_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,AFGCharacterPlayer,void __cdecl(float)>::ExecuteIfSafe() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:679]
FactoryGame_Win64_Shipping!TBaseMulticastDelegate<void,float>::Broadcast() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:977]
FactoryGame_Win64_Shipping!UWorld::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\leveltick.cpp:1726]
FactoryGame_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gameengine.cpp:1366]
FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:9]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4032]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launch.cpp:168]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
```

**Comment by Panakotta00** [comment] 2020-11-17 21:51
Can you try to cause the crash... and then open up SMM, go to "Debug" and then create a new debug file... plz then send this file... additionally plz fully describe what you do to get the issue.

**Comment by ebarboni** [comment] 2020-11-18 19:28
Hi, seems crash is not happening any more. Only client disconnect seems to be same as #104

**Comment by pottierg** [comment] 2020-11-18 19:31
Can confirm it looks like the same issues as #104, here is the dump debug info from SMM.
[SMMDebug_2020-11-18_19-29-15.zip](https://github.com/CoderDE/FicsIt-Networks/files/5562307/SMMDebug_2020-11-18_19-29-15.zip)

**Comment by Panakotta00** [comment] 2020-11-18 19:35
@pottierg are you sure? your debug file shows a crash caused by the power suit mod...

**Comment by pottierg** [comment] 2020-11-18 19:49
Here the debug file without Power Suit installed.
[Uploading SMMDebug_2020-11-18_19-49-12.zip…]()

**Comment by Panakotta00** [comment] 2020-11-18 19:52
OK... can you send the code you used @pottierg ? and why do you think it relates to #104 ? Doesn't your game crash? Isn't #104 about MP connection issue, not game crash?

**Comment by ebarboni** [comment] 2020-11-18 19:54
@Panakotta00 FYI, @pottierg is the client of my game, he cannot join in fact.

**Comment by Panakotta00** [comment] 2021-02-02 18:46
Should be fixed in the next update

**Closed by Panakotta00** 2021-02-02 18:46 UTC
Labels: bug
